apiVersion: v1
kind: Secret
metadata:
  name: wildcard.xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  namespace: csp
data:
  tls.crt: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  tls.key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
type: kubernetes.io/tls